const letter=new Set()
letter.add("ram")
letter.add("ragu")
letter.add("dravid")
console.log(letter)
letter.delete("ram")
console.log(letter)
console.log(letter.has("ragu"))
console.log(letter.values())